require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TownMediaController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TownMedium. As you add validations to TownMedium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TownMediaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all town_media as @town_media" do
      town_medium = TownMedium.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:town_media)).to eq([town_medium])
    end
  end

  describe "GET #show" do
    it "assigns the requested town_medium as @town_medium" do
      town_medium = TownMedium.create! valid_attributes
      get :show, {:id => town_medium.to_param}, valid_session
      expect(assigns(:town_medium)).to eq(town_medium)
    end
  end

  describe "GET #new" do
    it "assigns a new town_medium as @town_medium" do
      get :new, {}, valid_session
      expect(assigns(:town_medium)).to be_a_new(TownMedium)
    end
  end

  describe "GET #edit" do
    it "assigns the requested town_medium as @town_medium" do
      town_medium = TownMedium.create! valid_attributes
      get :edit, {:id => town_medium.to_param}, valid_session
      expect(assigns(:town_medium)).to eq(town_medium)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TownMedium" do
        expect {
          post :create, {:town_medium => valid_attributes}, valid_session
        }.to change(TownMedium, :count).by(1)
      end

      it "assigns a newly created town_medium as @town_medium" do
        post :create, {:town_medium => valid_attributes}, valid_session
        expect(assigns(:town_medium)).to be_a(TownMedium)
        expect(assigns(:town_medium)).to be_persisted
      end

      it "redirects to the created town_medium" do
        post :create, {:town_medium => valid_attributes}, valid_session
        expect(response).to redirect_to(TownMedium.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved town_medium as @town_medium" do
        post :create, {:town_medium => invalid_attributes}, valid_session
        expect(assigns(:town_medium)).to be_a_new(TownMedium)
      end

      it "re-renders the 'new' template" do
        post :create, {:town_medium => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested town_medium" do
        town_medium = TownMedium.create! valid_attributes
        put :update, {:id => town_medium.to_param, :town_medium => new_attributes}, valid_session
        town_medium.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested town_medium as @town_medium" do
        town_medium = TownMedium.create! valid_attributes
        put :update, {:id => town_medium.to_param, :town_medium => valid_attributes}, valid_session
        expect(assigns(:town_medium)).to eq(town_medium)
      end

      it "redirects to the town_medium" do
        town_medium = TownMedium.create! valid_attributes
        put :update, {:id => town_medium.to_param, :town_medium => valid_attributes}, valid_session
        expect(response).to redirect_to(town_medium)
      end
    end

    context "with invalid params" do
      it "assigns the town_medium as @town_medium" do
        town_medium = TownMedium.create! valid_attributes
        put :update, {:id => town_medium.to_param, :town_medium => invalid_attributes}, valid_session
        expect(assigns(:town_medium)).to eq(town_medium)
      end

      it "re-renders the 'edit' template" do
        town_medium = TownMedium.create! valid_attributes
        put :update, {:id => town_medium.to_param, :town_medium => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested town_medium" do
      town_medium = TownMedium.create! valid_attributes
      expect {
        delete :destroy, {:id => town_medium.to_param}, valid_session
      }.to change(TownMedium, :count).by(-1)
    end

    it "redirects to the town_media list" do
      town_medium = TownMedium.create! valid_attributes
      delete :destroy, {:id => town_medium.to_param}, valid_session
      expect(response).to redirect_to(town_media_url)
    end
  end

end
